# Generated by Django 5.2.5 on 2025-09-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redmart_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(default='default.png', upload_to='image/'),
            preserve_default=False,
        ),
    ]
